<?php

namespace ChildBundle\Repository;

/**
 * AttemptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttemptRepository extends \Doctrine\ORM\EntityRepository
{
}
