<?php

namespace ChildBundle\Repository;

/**
 * CartoonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartoonRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMatch($gender, $age){
        $qb= $this->createQueryBuilder('c')
            ->where('c.gender = :gender')
            ->orWhere('c.gender = 2')
            ->setParameter('gender', $gender);
        if($age >= 3 && $age <= 5 )
            $range = 1;
        else if($age > 5 && $age <= 8)
            $range = 2;
        else $range = 3;
        $qb->andWhere('c.age >= :range')
            ->setParameter('range', $range);
        return $qb->getQuery()->getResult();
    }
}
