<?php

namespace ChildBundle\Repository;

/**
 * ChildAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
