<?php

namespace ChildBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{

    public function findRelated($category){
        $qb = $this->createQueryBuilder('g')
            ->leftJoin('g.category', 'c')
            ->where('c.name = :category')
            ->setParameter('category', $category)
            ->setMaxResults(10);
        return $qb->getQuery()->getResult();
    }

    public function findAllowed($bans){
        $qb= $this->createQueryBuilder('g');
        if (count($bans) != 0)
            $qb->where($qb->expr()->notIn('g.id', $bans));
        return $qb->getQuery()->getResult();
    }

}
