<?php

namespace ChildBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findQuiz($id){
        $qb = $this->createQueryBuilder('qs')
            ->leftJoin('qs.quiz', "qz")
            ->where("qz.id = :id")
            ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
}
