<?php

namespace ShopBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArticle()
    {
        $q=$this->createQueryBuilder('m')
            ->where("m.type='Article'");
        return $q->getQuery()->getResult();
    }
}
