<?php

namespace ShopBundle\Repository;

/**
 * CouponsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponsRepository extends \Doctrine\ORM\EntityRepository
{
}
