<?php

namespace ShopBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function byFacture($user)
    {
        $qb = $this->createQueryBuilder('o')
            ->select('o')
            ->where('o.user = :user')
            ->andWhere('o.confirmed = 1')
            ->andWhere('o.reference != 0')
            ->orderBy('o.id')
            ->setParameter('user', $user);

        return $qb->getQuery()->getResult();
    }

//    public function getMax()
//    {   $statement= $this->getEntityManager()
//        ->getConnection()
//        ->prepare("SELECT  user_id,COUNT(*) as cou  from orders GROUP by user_id");
//        $statement->execute();
//        $results = $statement->fetchAll();
//        return $results;
//    }
    
}
