<?php

namespace ShopBundle\Repository;

/**
 * ProductOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOrderRepository extends \Doctrine\ORM\EntityRepository
{

    public  function findProfit($id){
        $qb = $this->createQueryBuilder('po')
            ->leftJoin('po.provider', 'pr')
            ->select('po.date as date')
            ->select('SUM(po.price) as income, SUM(po.quantity) as products, po.date, pr.id as provider')
            ->groupBy('po.date, pr.id')
            ->having('pr.id = :id')
            ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
}
