<?php

namespace ParentingBundle\Repository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategory($category)
    {
        $q=$this->createQueryBuilder('s')
            ->leftJoin('s.category', 'c')
            ->where("c.type ='Adresse'")
            ->andWhere('c.name = :category')
            ->orderBy('s.name')
            ->setParameter(':category',$category);
        return $q->getQuery()->getResult();
    }
    public function findAlphabet()
    {
        $q=$this->createQueryBuilder('m')
            ->orderBy('m.name');

        return $q->getQuery()->getResult();
    }

}
