<?php

namespace ParentingBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function findCategory($category)
    {
        $q=$this->createQueryBuilder('a')
            ->leftJoin('a.category', 'c')
            ->where("c.type = 'Article'")
            ->andWhere('c.id = :category')
            ->setParameter('category',$category);
        return $q->getQuery()->getResult();
    }

    public function findPlusVu()
    {
        $qb=$this->createQueryBuilder('a')
            ->orderBy('a.views')
            ->setMaxResults(3);
        return $qb->getQuery()->getResult();
    }

    public function findTitle($title)
    {
        $q=$this->createQueryBuilder('a')
            ->where('a.title LIKE :title')
            ->setParameter(':title',"%$title%");
        return $q->getQuery()->getResult();
    }



}
