<?php

namespace ParentingBundle\Repository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends \Doctrine\ORM\EntityRepository
{
    public function findClosest($lat, $lng)
    {
        $rsm = new ResultSetMappingBuilder($this->_em,ResultSetMappingBuilder::COLUMN_RENAMING_INCREMENT);
        $rsm->addRootEntityFromClassMetadata('ParentingBundle\Entity\School','s');
        $sql = " SELECT " . $rsm->generateSelectClause() . " FROM school s
			WHERE ( 6371 * acos( cos( radians(:lat) ) * cos( radians( lat ) ) * cos( radians( lng ) - radians(:lng) ) + sin( radians(:lat) ) * sin( radians( lat ) ) ) ) < 4";

        $query = $this->_em->createNativeQuery($sql, $rsm);
        $query->setParameter(':lat', $lat);
        $query->setParameter(':lng', $lng);

        return $query->getResult();
    }
}
