<?php

namespace ParentingBundle\Repository;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMarque($schoolname)
    {
        $q=$this->createQueryBuilder('m')
            ->where('m.schoolname LIKE :schoolname')
            ->setParameter(':schoolname',"%$schoolname%");
        return $q->getQuery()->getResult();
    }
}
