user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@UserBundle/Resources/config/admin-routes.yml"
    prefix:   /admin

events:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /

api_articles:
    resource: "@ParentingBundle/Resources/config/api-routes-mariem.yml"
    prefix:   /api
api_complaints:
    resource: "@UserBundle/Resources/config/api-routes.yml"
    prefix:   /api

api_events:
    resource: "@EventsBundle/Resources/config/api-routes.yml"
    prefix:   /api

child:
    resource: "@ChildBundle/Resources/config/routing.yml"
    prefix:   /

api_child:
    resource: "@ChildBundle/Resources/config/api-routes.yml"
    prefix:   /api

parenting:
    resource: "@ParentingBundle/Resources/config/routing.yml"
    prefix:   /

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /

media:
    resource: "@MediaBundle/Resources/config/routing.yml"
    prefix:   /

api_parent_routes :
    resource: "@ParentingBundle/Resources/config/api-routes.yml"
    prefix: /api

api_read_videos:
    resource: "@MediaBundle/Resources/config/api-routes.yml"
    prefix: /api

api_map:
    resource: "@ParentingBundle/Resources/config/api-routes.yml"
    prefix: /api

api_more:
    resource: "@ParentingBundle/Resources/config/api-routes.yml"
    prefix: /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor

api_login_check:
    path: /api/login_check