<?php

namespace UserBundle\Repository;

/**
 * ComplaintCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplaintCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
