<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function byFournisseur()
    {
        $qb = $this->createQueryBuilder('r')
            ->where('r.roles LIKE :roles')
            ->setParameter(':roles',"%ROLE_PROVIDER%");
        return $qb->getQuery()->getResult();
    }





}
