read_teachers:
    path:     /teachers/read
    defaults: { _controller: parentiingBundle:Teacher:readteachers }

teacher_add:
    path:     admin/teacher/add
    defaults: { _controller: parentiingBundle:Teacher:create }

delete_prof:
    path:     admin/delete{id}
    defaults: { _controller: parentiingBundle:Teacher:delete }

read_teachers1:
        path:     admin/delete
        defaults: { _controller: parentiingBundle:Teacher:readteachers1 }

subject_add:
    path:     subject/add
    defaults: { _controller: parentiingBundle:Subject:create }

update_teacher:
    path:     /teacher/update{id}
    defaults: { _controller: parentiingBundle:Teacher:updateteacher }
