video_add:
    path:     /admin/video/add
    defaults: { _controller: MediaBundle:Video:createvideo}

video_read:
    path:     /video/read
    defaults: { _controller: MediaBundle:Video:readvid}

save_photo :
    path:   /photo/save
    defaults: { _controller:  MediaBundle:Photo:savePhoto }