user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Home:index }

edit_profile:
    path:     /profile/manage
    defaults: { _controller: UserBundle:Home:editProfile }

create_complaint:
    path:     /parent/complaint/create
    defaults: { _controller: UserBundle:Complaint:create }

read_complaint:
    path:     /admin/Complaint/read
    defaults: { _controller: UserBundle:Complaint:read }

update_complaint:
    path:     /admin/Complaint/update{id}
    defaults: { _controller: UserBundle:Complaint:update }

delete_complaint:
    path:     /admin/Complaint/delete{id}
    defaults: { _controller: UserBundle:Complaint:delete }

list_complaints:
    path:     /parent/complaints
    defaults: { _controller: UserBundle:Complaint:front_read }

create_category:
    path:     /parent/Complaint/Category/Add
    defaults: { _controller: UserBundle:Complaint:add_category }

bills:
    path: /profile/bills
    defaults: { _controller: UserBundle:Users:bills }

api_user_get:
    path: /api/user/get
    defaults : { _controller: UserBundle:Users:getUser }

api_subscribe:
    path: /registerapi
    defaults: { _controller:  UserBundle:Users:subscribeApi }
    methods: POST

add_users:
    path: /users/add
    defaults : { _controller: UserBundle:Admin:addUsers }


