shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }

create_product:
    path:     /provider/products/create
    defaults: { _controller: ShopBundle:ProductProvider:createProduct }

update_product:
    path:     /provider/products/update/{id}
    defaults: { _controller: ShopBundle:ProductProvider:updateProduct }

show_products:
    path:     /provider/products
    defaults: { _controller: ShopBundle:ProductProvider:showProduct }

delete_product:
    path:     /provider/products/delete/{id}
    defaults: { _controller: ShopBundle:ProductProvider:deleteProduct }

product_blk_delete:
    path:     /provider/products/delete
    defaults: { _controller: ShopBundle:ProductProvider:deleteProductBulk }

add_category:
    path:     /admin/categories/add
    defaults: { _controller: ShopBundle:Category:addCategory }

show_category:
    path:     /admin/categories
    defaults: { _controller: ShopBundle:Category:showCategory }

category_blk_delete:
    path:     /admin/categories/delete
    defaults: { _controller: ShopBundle:Category:deletCategoryBulk }

categories_list:
    path:     /parent/categories
    defaults: { _controller: ShopBundle:Product:listCategories }

product_bycategory:
    path:     /parent/products/category/{category}
    defaults: { _controller: ShopBundle:Product:categorie }

infoProduits:
    path:     /parent/products/{id}
    defaults: { _controller: ShopBundle:Product:infoProduit }

ajouterpanier:
    path:     /parent/cart/add/{id}
    defaults: { _controller: ShopBundle:Panier:ajouterpanier }

supprimerpanier:
    path:     /parent/cart/delete/{id}
    defaults: { _controller: ShopBundle:Panier:supprimerpanier }

panier:
    path:     /parent/cart
    defaults: { _controller: ShopBundle:Panier:panier }

read_fournisseur:
    path:     /admin/providers
    defaults: { _controller: ShopBundle:Fournisseur:readFournisseur }

create_fournisseur:
    path:     /admin/providers/add
    defaults: { _controller: ShopBundle:Fournisseur:createFournisseur }
