shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }

api_order_confirm:
    path:      /bank/{id}
    defaults: { _controller: ShopBundle:Orders:confirmation }

search_product:
    path:     /products/search
    defaults: { _controller : ShopBundle:Products:search }

product_details:
    path:     /products/{id}
    defaults: { _controller: ShopBundle:Products:details }

products:
    path:     /products
    defaults: { _controller: ShopBundle:Products:products }

product_bycategory:
    path:     /products/category/{category}
    defaults: { _controller: ShopBundle:Products:category }

parent_routes:
    resource:   '@ShopBundle/Resources/config/parent.yml'
    prefix:     /parent

provider_routes:
    resource:   '@ShopBundle/Resources/config/provider.yml'

admin_routes:
    resource:   '@ShopBundle/Resources/config/admin.yml'
    prefix:     /admin

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    defaults: { _format: html }



