services:
#     redirectionListener:
#        class: KODproject\ShopBundle\Listener\RedirectionListener
#        arguments: ['@service_container','@session']
#        tags:
#           - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
      setNewReference:
          class:     ShopBundle\Services\GetReference
          arguments: ['@security.authorization_checker', '@doctrine.orm.entity_manager']