create_babysitter:
    path:     /babysitter/create
    defaults: { _controller: ParentingBundle:Babysitter:create }

read_babysitter:
    path:     /babysitter/read
    defaults: { _controller: ParentingBundle:Babysitter:read }

update_babysitter:
    path:    /babysitter/update/{id}
    defaults: { _controller: ParentingBundle:Babysitter:update }

delete_babysitter:
    path:    /babysitter/delete/{id}
    defaults: { _controller: ParentingBundle:Babysitter:delete }

create_address:
    path:     /address/create
    defaults: { _controller: ParentingBundle:Address:create }

delete_address:
    path:     /address/delete/{id}
    defaults: { _controller: ParentingBundle:Address:delete }

read_address:
    path:     /address/read
    defaults: { _controller: ParentingBundle:Address:read }

update_address:
    path:     /address/update/{id}
    defaults: { _controller: ParentingBundle:Address:update }

map_address:
    path:     /address/map
    defaults: { _controller: ParentingBundle:Address:map }

map2_address:
    path:     /address/map2
    defaults: { _controller: ParentingBundle:Address:map2 }

update:
    path:     /article/update/{id}
    defaults: { _controller: ParentingBundle:Article:update }

delete:
    path:     /article/delete/{id}
    defaults: { _controller: ParentingBundle:Article:delete }
read:
    path:     /article/read
    defaults: { _controller: ParentingBundle:Article:read }

create:
    path:     /article/create
    defaults: { _controller: ParentingBundle:Article:create }

read_school:
        path: /schools
        defaults: { _controller: ParentingBundle:School:listSchool }

delete_school:
    path:     /schools/delete{id}
    defaults: { _controller: ParentingBundle:School:delete }

school_add:
    path:     /schools/add
    defaults: { _controller: ParentingBundle:School:createSchool }

school_update:
    path:     /schools/update/{id}
    defaults: { _controller: ParentingBundle:School:updateSchool }

list_teachers:
        path: /teachers
        defaults: { _controller: ParentingBundle:Teacher:listTeachers }

update_teacher:
    path:     /teacher/update{id}
    defaults: { _controller: ParentingBundle:Teacher:updateteacher }

teacher_add:
    path:     /teacher/add
    defaults: { _controller: ParentingBundle:Teacher:create }

delete_teacher:
    path:     /teacher/delete{id}
    defaults: { _controller: ParentingBundle:Teacher:delete }

subject_add:
    path:     /subject/add
    defaults: { _controller: ParentingBundle:Subject:create }