front_read_babysitter:
    path:     /Babysitter/read
    defaults: { _controller: ParentingBundle:Babysitter:front_read }

contact_babysitter:
    path:    /Babysitter/contact{id}
    defaults: { _controller: ParentingBundle:Babysitter:contact }

mail_babysitter:
        path:    /Babysitter/Mail{name}
        defaults: { _controller: ParentingBundle:Babysitter:Mail }

front_addresses:
    path:     /addresses/
    defaults: { _controller: ParentingBundle:Address:front_read }

more_addresses:
    path:     /adresses/{id}
    defaults: { _controller: ParentingBundle:Address:more }

categories_addresses:
    path:     /address/category/{category}
    defaults: { _controller: ParentingBundle:Address:showbyCategory }

front_read:
    path:     /aide/article/read
    defaults: { _controller: ParentingBundle:Article:frontRead }

more:
    path:     /aide/article/more/{id}
    defaults: { _controller: ParentingBundle:Article:more }

search_article:
    path:   /aide/article/search
    defaults: { _controller: ParentingBundle:Article:search }

show_by_category:
        path:   /aide/article/category/show/{category}
        defaults: { _controller: ParentingBundle:Article:showbyCategory }

read_teachers:
    path:     /teachers/read
    defaults: { _controller: ParentingBundle:Teacher:readteachers }

teacher_add:
    path:     admin/teacher/add
    defaults: { _controller: ParentingBundle:Teacher:create }

delete_prof:
    path:     admin/teacher/delete{id}
    defaults: { _controller: ParentingBundle:Teacher:delete }

read_teachers1:
        path:     admin/teacher/delete
        defaults: { _controller: ParentingBundle:Teacher:readteachers1 }

subject_add:
    path:     subject/add
    defaults: { _controller: ParentingBundle:Subject:create }

update_teacher:
    path:     /teacher/update{id}
    defaults: { _controller: ParentingBundle:Teacher:updateteacher }

school_add:
    path:     admin/school/add
    defaults: { _controller: ParentingBundle:School:createSchool }

delete_school:
    path:     school/delete{id}
    defaults: { _controller: ParentingBundle:School:delete }

read_school1:
        path:     admin/school/delete
        defaults: { _controller: ParentingBundle:School:readschool1 }

look_school:
        path:     see
        defaults: { _controller: ParentingBundle:School:readschool1 }

map:
  path:    /mapschool/
  defaults: { _controller: ParentingBundle:School:map}

recherche_school:
    path:     /find/school
    defaults: { _controller: ParentingBundle:School:Recherche}

about_teacher:
    path:    /teacher/about{id}
    defaults: { _controller: ParentingBundle:Teacher:about }
