contact_babysitter:
    path:    /Babysitter/contact{id}
    defaults: { _controller: ParentingBundle:Babysitter:contact }

mail_babysitter:
        path:    /Babysitter/Mail{name}
        defaults: { _controller: ParentingBundle:Babysitter:Mail }

front_addresses:
    path:     /addresses/
    defaults: { _controller: ParentingBundle:Address:front_read }

more_addresses:
    path:     /adresses/{id}
    defaults: { _controller: ParentingBundle:Address:more }

categories_addresses:
    path:     /address/category/{category}
    defaults: { _controller: ParentingBundle:Address:showbyCategory }

map:
  path:    /mapschool/
  defaults: { _controller: ParentingBundle:School:map}

recherche_school:
    path:     /find/school
    defaults: { _controller: ParentingBundle:School:Recherche}

about_teacher:
    path:    /teacher/about/{id}
    defaults: { _controller: ParentingBundle:Teacher:teacherDetails}

read_teachers:
    path:    /teachers
    defaults: { _controller: ParentingBundle:Teacher:readteachers}
