parenting_homepage:
    path:     /
    defaults: { _controller: ParentingBundle:Default:index }

create_babysitter:
    path:     /Admin/Babysitter/create
    defaults: { _controller: ParentingBundle:Babysitter:create }

read_babysitter:
    path:     /Admin/Babysitter/read
    defaults: { _controller: ParentingBundle:Babysitter:read }
front_read_babysitter:
    path:     /Parent/Babysitter/read
    defaults: { _controller: ParentingBundle:Babysitter:front_read }
update_babysitter:
    path:    /Admin/Babysitter/update{id}
    defaults: { _controller: ParentingBundle:Babysitter:update }

delete_babysitter:
    path:    /Admin/Babysitter/delete/{id}
    defaults: { _controller: ParentingBundle:Babysitter:delete }

contact_babysitter:
    path:    /Parent/Babysitter/contact{id}
    defaults: { _controller: ParentingBundle:Babysitter:contact }
