parenting_homepage:
    path:     /
    defaults: { _controller: ParentingBundle:Default:index }

create_babysitter:
    path:     /Admin/Babysitter/create
    defaults: { _controller: ParentingBundle:Babysitter:create }

read_babysitter:
    path:     /Admin/Babysitter/read
    defaults: { _controller: ParentingBundle:Babysitter:read }
front_read_babysitter:
    path:     /Parent/Babysitter/read
    defaults: { _controller: ParentingBundle:Babysitter:front_read }

update_babysitter:
    path:    /Admin/Babysitter/update{id}
    defaults: { _controller: ParentingBundle:Babysitter:update }

delete_babysitter:
    path:    /Admin/Babysitter/delete/{id}
    defaults: { _controller: ParentingBundle:Babysitter:delete }

contact_babysitter:
    path:    /Parent/Babysitter/contact{id}
    defaults: { _controller: ParentingBundle:Babysitter:contact }


read_teachers:
    path:     /teachers/read
    defaults: { _controller: ParentingBundle:Teacher:readteachers }

teacher_add:
    path:     admin/teacher/add
    defaults: { _controller: ParentingBundle:Teacher:create }

delete_prof:
    path:     admin/teacher/delete{id}
    defaults: { _controller: ParentingBundle:Teacher:delete }

read_teachers1:
        path:     admin/teacher/delete
        defaults: { _controller: ParentingBundle:Teacher:readteachers1 }

subject_add:
    path:     subject/add
    defaults: { _controller: ParentingBundle:Subject:create }

update_teacher:
    path:     /teacher/update{id}
    defaults: { _controller: ParentingBundle:Teacher:updateteacher }

school_add:
    path:     admin/school/add
    defaults: { _controller: ParentingBundle:School:createSchool }

delete_school:
    path:     school/delete{id}
    defaults: { _controller: ParentingBundle:School:delete }

read_school1:
        path:     admin/school/delete
        defaults: { _controller: ParentingBundle:School:readschool1 }

look_school:
        path:     see
        defaults: { _controller: ParentingBundle:School:readschool1 }


map:
  path:    /Parent/mapschool/
  defaults: { _controller: ParentingBundle:School:map}

recherche_school:
    path:     /find/school
    defaults: { _controller: ParentingBundle:School:Recherche}

about_teacher:
    path:    /Parent/teacher/about{id}
    defaults: { _controller: ParentingBundle:Teacher:about }

mail_babysitter:
        path:    /Parent/Babysitter/Mail{name}
        defaults: { _controller: ParentingBundle:Babysitter:Mail }

create_address:
    path:     /Admin/Address/Create
    defaults: { _controller: ParentingBundle:Address:create }

delete_address:
    path:     /Admin/Address/Delete{id}
    defaults: { _controller: ParentingBundle:Address:delete }

read_address:
    path:     /Admin/Address/Read
    defaults: { _controller: ParentingBundle:Address:read }

update_address:
    path:     /Admin/Address/Update{id}
    defaults: { _controller: ParentingBundle:Address:update }

map_address:
    path:     /Admin/Address/map
    defaults: { _controller: ParentingBundle:Address:map }

map2_address:
    path:     /Admin/Address/map2
    defaults: { _controller: ParentingBundle:Address:map2 }

front_addresses:
    path:     /Parent/Address/List
    defaults: { _controller: ParentingBundle:Address:front_read }

discutea_forum:
    resource: "@DForumBundle/Resources/config/routing.yml"
    prefix:   /

more_addresses:
    path:     /Parent/Address/more{id}
    defaults: { _controller: ParentingBundle:Address:more }
categories_addresses:
    path:     /Parent/Address/Category/{category}
    defaults: { _controller: ParentingBundle:Address:showbyCategory }


