discutea_forum:
    resource: "@DForumBundle/Resources/config/routing.yml"

kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messaging

admin_routes :
    resource: "@ParentingBundle/Resources/config/admin.yml"
    prefix: /admin

parent_routes :
    resource: "@ParentingBundle/Resources/config/parent.yml"
    prefix: /parent

#--------------Babysitters
list_babysitters:
    path:     /babysitters
    defaults: { _controller: ParentingBundle:Babysitter:list }

#-------------Articles

view_article:
    path:     /aide/article/more/{id}
    defaults: { _controller: ParentingBundle:Article:view }

list_articles:
    path:     /aide/articles
    defaults: { _controller: ParentingBundle:Article:list }

search_article:
    path:   /aide/article/search
    defaults: { _controller: ParentingBundle:Article:search }

show_by_category:
    path:   /aide/article/category/{id}
    defaults: { _controller: ParentingBundle:Article:showbyCategory }


