discutea_forum:
    resource: "@DForumBundle/Resources/config/routing.yml"

kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messaging

admin_routes :
    resource: "@ParentingBundle/Resources/config/admin.yml"
    prefix: /admin

parent_routes :
    resource: "@ParentingBundle/Resources/config/parent.yml"
    prefix: /parent


