<?php

namespace MediaBundle\Repository;

/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MThreadRepository extends \Doctrine\ORM\EntityRepository
{
}
