<?php

namespace MediaBundle\Repository;

/**
 * ThreadMetadataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MThreadMetadataRepository extends \Doctrine\ORM\EntityRepository
{
}
