<?php

namespace MediaBundle\Repository;

/**
 * MusicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllowed($bans){
        $qb= $this->createQueryBuilder('m');
        if (count($bans) != 0)
            $qb->where($qb->expr()  ->notIn('m.id', $bans));
        return $qb->getQuery()->getResult();
    }
}
