<?php

namespace MediaBundle\Repository;

/**
 * videoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class videoRepository extends \Doctrine\ORM\EntityRepository
{

}
